### ISSUE TITLE
PM Review #1: Design Documents/Wiki

### ISSUE THREAD

**Issue by andrewlangston** [yev-reym/FloatingNote#1]
Hi Eugene,

Great job with your design documents. Some preliminary comments on what you've been assigned thus far (MVP list, schema, sample state):

**MVP LIST**
- [x] There is some conflation of features going on with your MVP timeline. Broadly speaking, the central features required of Soundcloud are below (and should be completed in this order). Please take some time to refactor accordingly:
  - Song CRUD (creating/uploading, reading/displaying, updating/editing, destroying/deleting)
  - Playing songs with progress bar & continuous play as user navigates around the app
  - Comments on songs
  - User profile pages

**SCHEMA**
- [x] Your `users` table should include `gender` and `age` columns, as required by Soundcloud itself.
- [x] Your `tracks` table need not include `image_url` and `track_url` - these will be handled via Amazon Web Services and ActiveStorage (more on this next week). I think you can also hold off on `description` and `private` status for the time being.
- [x] Soundcloud permits nested comments, so your `comments` table should include an optional `parent_comment_id` column.

**SAMPLE STATE**
- [x] Rather than your `users` maintaining references to commented tracks via an array of `commentedTracks`, I think it would make more sense to reference the comments themselves (via, for example, `commentIds`). This will be important because your comments carry information beyond author & track - they also hold a reference to a timestamp within a track.
- [x] These reference arrays, in general, should be named as semantically as possible. I would suggest, for example - changing the `comments` key in your `tracks` slice of state to `commentIds`, `likedUsers` to 'likerIds`, etc.
- [x] `trackComments` seems redundant - let's cleave close to the schema here and simply call this slice of state `comments`.

Let me know if you have any questions!

**Comment by andrewlangston** [comment]
Eugene - please see below for additional comments regarding your route design documents. Let me know when you have had a chance to address these. Thanks!

**BACKEND ROUTES**
- [ ] We won't ask that you implement the editing of user profiles (though I would encourage you to consider it as a bonus). Feel free to remove `PATCH /api/users/:user_id`.
- [ ] I don't think you will need `GET /api/comments/:comment_id`, as you will never have to fetch one comment at a time - they will always be fetched collectively for a track.

**FRONTEND ROUTES**
- [ ] Soundcloud uses modals for signup/login, so we won't need separate frontend routes for these.
- [ ] Soundcloud displays a track index at the frontend route `/discover` - this is easy enough to implement, so please do the same (instead of `/tracks`).

**Comment by yev-reym** [comment]
Hey Andrew,
  Thank you for the feedback. I understand what you mean by our modal encompassing both the login and sign up, but i am not quite sure under what route to put it under, and I am second guessing my frontend routes now. If we could just have a quick discussion about the frontend part, that would be great.

**Comment by andrewlangston** [comment]
Eugene - not a problem. Because login/signup are handled via modal, they will display on the same route as your splash page, i.e., `/`. The contents of the URL bar will not change.

That said, we can absolutely sit down to discuss the rest of your design documents - if not later today, then certainly tomorrow before you dive deep into building this out.
